### ISSUE TITLE
Errorously parsing Bruker *.fid

### ISSUE THREAD

**Issue by hsiaoyi0504** [sgibb/readBrukerFlexData#3]
When I read the *.fid, I got a wrong parsing. As you can see in following figures:

When I read the bruker *.fid, I got this
![before_bruker](https://cloud.githubusercontent.com/assets/10943928/21467784/2e196440-ca34-11e6-8f0f-5827fb28e4eb.png)

But if I read the transformed *.mzxml, I got this
![after_mzxml](https://cloud.githubusercontent.com/assets/10943928/21467785/3647438a-ca34-11e6-9328-88c95bf3aa71.png)

There is a shift in m/z. After suspected the file in bruker software, I found the first one is wrong. For your reference, I also attached the input files here. 
[0_P10.mzXML.zip](https://github.com/sgibb/MALDIquantForeign/files/671828/0_P10.mzXML.zip)
[0_P10.zip](https://github.com/sgibb/MALDIquantForeign/files/671829/0_P10.zip)

**Comment by SamGG** [comment]
Same problem. Does anybody ask Bruker directly?

**Comment by sgibb** [comment]
Back in 2010 and in early 2011 when I started the development of `readBrukerFlexData` I had some conversations with two developers and an official speaker from Bruker (about HPC). They weren't allowed to give me any details on the file format.
I assume that this attitude didn't changed but I don't know for sure.

**Comment by SamGG** [comment]
Bruker's policy didn't change. The polynomial equation is confirmed. HPC is patented without any communication.

I spent hours at understanding the question. I think I reached some conclusions (see 2nd next comment, thanks @sgibb for the equation coefficients). I need some help to finish...

I would like a spectra with a fifth calibration coefficient not zero. The one of @hsiaoyi0504 seems problematic to me (next comment).

I would like some feedback from whoever is listening here.

Best,
Samuel

**Comment by SamGG** [comment]
The file from @hsiaoyi0504 but still don't understand it. What is surprising is the shape of the transformation. I plotted the sqrt(m/z) from the mzXML versus tof and the curve at low tof is somehow odd for me.

![image](https://user-images.githubusercontent.com/3333348/95339451-5e0d5680-08b4-11eb-9684-c4cdf6bb4a62.png)

**Comment by SamGG** [comment]
```
library("readBrukerFlexData")
library("readMzXmlData")

f <- readBrukerFlexFile("spectra_P10/0_P10/1/1Ref/fid")
m <- readMzXmlFile("0_P10.mzXML")

tof <- f$spectrum$tof
mz <- m$spectrum$mass

range(tof)
range(mz)

length(tof)
length(mz)

(idx = as.integer(seq(1, length(tof), length.out = 100)))

tof = tof[idx]
mz  = mz[idx]

plot(tof, mz)
plot(tof, sqrt(mz))


##$NTBCal= <V3.0CCalibrator 12 1 0 0 -2147483648 2147483647  V1.0CHPCData  Order 0 vCoeff V1.0VectorDouble 0  c2 0 c0 0 minMass 0 maxMass 0 bUse 0 endCHPCData V1.0CTOF2CalibrationConstants 48 0.25 3884.868239229128 1164156.9998801197 6.1682474689786355 -0.063083671657452864 -34.362308485323794 2 V1.0CTOF2CalibrationConstants 0 0 0 0 0 0 0 -1  > 
##$NTBCalr= <V3.0CCalibrator 12 1 0 0 -2147483648 2147483647  V1.0CHPCData  Order 0 vCoeff V1.0VectorDouble 0  c2 0 c0 0 minMass 0 maxMass 0 bUse 0 endCHPCData V1.0CTOF2CalibrationConstants 48 0.25 3884.868239229128 1164156.9998801197 6.1682474689786355 -0.063083671657452864 -34.362308485323794 2 V1.0CTOF2CalibrationConstants 48 0.25 3884.868239229128 1164156.9998801197 6.1682474689786355 -0.063083671657452864 -34.362308485323794 2> 

Calib = c(3884.868239229128, sqrt(1e12/1164156.9998801197), 6.1682474689786355, -0.063083671657452864, -34.362308485323794, 2)

df <- data.frame(tof=tof,x=sqrt(mz))
plot(df$tof, df$x)
```

I didn't succeed in fitting it with the equation, but the equation is OK if the fifth coefficient is zero. This means the equation is cubic instead of 4th order. In fact, @sgibb has nearly get the correct equation except he switched the last two coefficients (D<=>E). Here is my code and a test file (matrix control).

``` r
library("readBrukerFlexData")
library("readMzXmlData")
#> Warning: package 'readMzXmlData' was built under R version 4.0.2

# define file location and read
setwd("C:/data/active/tests/test-bruker/")
f <- readBrukerFlexFile("spectra_D23/0_D23/1/1SLin/fid")
#> Warning in .readAcquFile(fidFile = fidFile, verbose = verbose): File 'C:
#> \data\active\tests\test-bruker\spectra_D23\0_D23\1\1SLin\fid' seems to be empty
#> because no laser shots applied to this sample.
#> Warning in readBrukerFlexFile("spectra_D23/0_D23/1/1SLin/fid"): The spectrum file 'C:\data\active\tests\test-bruker\spectra_D23\0_D23\1\1SLin\fid' uses V1.0CTOF2CalibrationConstants.
#> V1.0CTOF2CalibrationConstants aren't supported by readBrukerFlexFile. See https://github.com/sgibb/MALDIquantForeign/issues/19 for details.
#> Could not convert time-of-flight values into mass!
m <- readMzXmlFile("spectra_D23.mzXML")  # converted using ProteoWizard

# extract information
tof <- f$spectrum$tof
mz <- m$spectrum$mass

range(tof)
#> [1] 13987.0 94812.6
range(mz)
#> [1]   399.9186 19933.5835

length(tof)
#> [1] 50517
length(mz)
#> [1] 50517

# sample 100 points
(idx = as.integer(seq(1, length(tof), length.out = 100)))
#>   [1]     1   511  1021  1531  2042  2552  3062  3572  4083  4593  5103  5613
#>  [13]  6124  6634  7144  7654  8165  8675  9185  9695 10206 10716 11226 11737
#>  [25] 12247 12757 13267 13778 14288 14798 15308 15819 16329 16839 17349 17860
#>  [37] 18370 18880 19390 19901 20411 20921 21432 21942 22452 22962 23473 23983
#>  [49] 24493 25003 25514 26024 26534 27044 27555 28065 28575 29085 29596 30106
#>  [61] 30616 31127 31637 32147 32657 33168 33678 34188 34698 35209 35719 36229
#>  [73] 36739 37250 37760 38270 38780 39291 39801 40311 40822 41332 41842 42352
#>  [85] 42863 43373 43883 44393 44904 45414 45924 46434 46945 47455 47965 48475
#>  [97] 48986 49496 50006 50517

tof = tof[idx]
mz  = mz[idx]

# overview
plot(tof, mz)
```

![](https://i.imgur.com/WdeE1tX.png)

``` r
plot(tof, sqrt(mz))
```

![](https://i.imgur.com/JMQdp0G.png)

``` r

# extract from the acqu file
##$NTBCal= <V3.0CCalibrator 12 1 0 0 -2147483648 2147483647  V1.0CHPCData  Order 0 vCoeff V1.0VectorDouble 0  c2 0 c0 0 minMass 0 maxMass 0 bUse 0 endCHPCData V1.0CTOF2CalibrationConstants 13987.200000000001 1.5999999999999999 581.41079117084337 2220702.4352394971 -0.036090927547664166 7.3810763208576876e-005 0 2 V1.0CTOF2CalibrationConstants 13987.200000000001 1.5999999999999999 581.41079117084337 2220702.4352394971 -0.036090927547664166 7.3810763208576876e-005 0 2  > 
##$NTBCalr= <V3.0CCalibrator 12 1 0 0 -2147483648 2147483647  V1.0CHPCData  Order 0 vCoeff V1.0VectorDouble 0  c2 0 c0 0 minMass 0 maxMass 0 bUse 0 endCHPCData V1.0CTOF2CalibrationConstants 13987.200000000001 1.5999999999999999 581.41079117084337 2220702.4352394971 -0.036090927547664166 7.3810763208576876e-005 0 2 V1.0CTOF2CalibrationConstants 13987.200000000001 1.5999999999999999 581.41079117084337 2220702.4352394971 -0.036090927547664166 7.3810763208576876e-005 0 2  > 

# define the calibration coefficients
Calib = c(581.41079117084337, sqrt(1e12/2220702.4352394971), -0.036090927547664166, 7.3810763208576876e-005, 0, 2)


# model of the data
df <- data.frame(tof=tof,x=sqrt(mz))

(mod2 = lm(tof ~ 1 + I(x) + I(x^2), data=df))
#> 
#> Call:
#> lm(formula = tof ~ 1 + I(x) + I(x^2), data = df)
#> 
#> Coefficients:
#> (Intercept)         I(x)       I(x^2)  
#>   606.45893    669.77815     -0.01825
Calib[1:3]
#> [1] 581.41079117 671.04989940  -0.03609093

# the coefficients perfectly match the coefficients found by a linear fit
(mod4 = lm(tof ~ 1 + I(x) + I(x^2) + I(x^3) + I(x^4), data=df))
#> 
#> Call:
#> lm(formula = tof ~ 1 + I(x) + I(x^2) + I(x^3) + I(x^4), data = df)
#> 
#> Coefficients:
#> (Intercept)         I(x)       I(x^2)       I(x^3)       I(x^4)  
#>   5.812e+02    6.710e+02   -3.609e-02    7.381e-05   -7.016e-18
Calib[1:5]
#> [1]  5.814108e+02  6.710499e+02 -3.609093e-02  7.381076e-05  0.000000e+00

# graphical view
plot(df$x, df$tof)
lines(df$x, predict(mod2), col = 2, lw = 2)
lines(df$x, predict(mod4), col = 4, lw = 2)
```

![](https://i.imgur.com/dHVlbLE.png)

``` r

# error on the estimated tof is very small, < 8e-11
plot(df$x, predict(mod4) - df$tof)
```

![](https://i.imgur.com/1nRUD5q.png)

<sup>Created on 2020-10-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by SamGG** [comment]
Final thought: using a cubic or 4th order (aka "enhanced cubic" as called by Bruker IIUC) is interesting. I showed that we interpret the equation to some extent (up to 3th order). I did a verification that the m/z equation equals the tof. I did not solve the equation in order to compute the m/z from the equation and the tof values. When the equation was of 2nd order, there is a symbolic solution, the one stated by @sgibb . Higher orders imply the use of polyroot function to solve the equation for sqrt(mz). I think we could solve the equation for 1000 points and interpolate the values between them. But there are maybe better solutions.

```r
# only 2nd order coefficients
# 0 = A * (sqrt(mz))^2 + B * sqrt(mz) + C(tof)
Re(polyroot(c(Calib[1]-tof[1], Calib[2], Calib[3])))^2
Re(polyroot(c(Calib[1]-tof[length(tof)], Calib[2], Calib[3])))^2
```

**Comment by sgibb** [comment]
@SamGG thanks a lot for looking into it! Can you share your test files? Your work is already an improvement. Instead of not converting any `tof` to `mz` if `V1.0CTOF2CalibrationConstants` is present in the `acqu` file we could at least convert up to 3th order polynomials.

**Comment by czanetti** [comment]
Same problem here, I need to use the cubic enhanced calibration to get decent mass accuracies but also want to keep the metadata from readBrukerFlexData since it is very useful.
If I am not misunderstood, there was some progress but we are not there yet for the _exact_ conversion, I also gave it a try but soon found out it is not an easy task.

I was thinking of a workaround, do you people think this approach is reliable?
1. use the spectra calibrated with the cubic enhanced equation (or any other unsupported calibration)
2. export the valid m/z spectra in ASCII or other open formats (e.g flexAnalysis supports batch exporting in ASCII, retaining sample name and fid path)
3. read the acquired data (fid) with readBrukerFlexData to get all the metadata into R (but wrong m/z values)
4. substitute the mass and intensity values stored by readBrukerFlexData with the correct ASCII values

Another more elegant/reliable idea could be to store the metadata from the acqu(s) file into mzML or mzXML files, do you think this is feasible? (compassXport documentation is not so user friendly, but it seems to me that this FlexVariableTable.xml may be useful)

or if anybody has suggestions for other workarounds to keep the metadata I would greatly appreciat that.

Thanks for the great contributions!
 Best,
 Cristian

**Comment by FrederikHolck** [comment]
Hi,
We've recently run into the same issue with bruker flex data and V1.0CTOF2CalibrationConstants not being supported and read by readBrukerFlexFile. Are there any news on the development?
I'm afraid I'm not qualified to help in any way. We simply wish to read bruker flex data and export to MSD files.
Best,
Frederik

**Comment by sgibb** [comment]
Unfortunately not. You just could use the Bruker software to export fid to mzML and use `MALDIquantForeign` to import this mzML and export it to MSD.

**Comment by AlanRace** [comment]
I think the final variable may be some form of constant correction to the resulting `m/z`. That would explain why when this value is 0, the cubic equation fits (as @SamGG showed).

```r
library("readBrukerFlexData")
library("readMzXmlData")

f <- readBrukerFlexFile("0_P10/1/1Ref/fid") #, filterZeroIntensities=TRUE)
m <- readMzXmlFile("0_P10.mzXML")

A <- 6.1682474689786355
B <- sqrt(1e12/1164156.9998801197)
C <- 3884.868239229128
D <- -0.063083671657452864
E <- -34.362308485323794

mz <- m$spectrum$mass
tof <- f$spectrum$tof

mzPlusE = mz + E
sign = ((mzPlusE > 0) * 2)-1

df <- data.frame(tof=tof,x=sqrt(abs(mzPlusE))*sign) 

(mod4 = lm(tof ~ 1 + I(x) + I(x^2) + I(x^3), data=df))

plot(df$x, df$tof)
lines(df$x, predict(mod4), col = 2, lw = 2)
```
![x_vs_tof](https://user-images.githubusercontent.com/1210117/161781092-da0bbf93-c24d-49af-8586-9335d4073ff7.png)

I don't get the exact coefficients, but fairly close:

```
Call:
lm(formula = tof ~ 1 + I(x) + I(x^2) + I(x^3), data = df)

Coefficients:
(Intercept)         I(x)       I(x^2)       I(x^3)  
 3845.78915    934.56039      5.79341     -0.05795  
```

```
3884.8682    926.8175    6.16824    -0.0630
```

**Comment by AlanRace** [comment]
A little more detail. The following (cubic transform) seems to produce the correct `m/z`s for the 'upper' mass range (i.e. above the `m/z` dictated by the final coefficient).

```r
library('AlgebraicHaploPackage')
library("readBrukerFlexData")
library("readMzXmlData")

f <- readBrukerFlexFile("0_P10/1/1Ref/fid") 
m <- readMzXmlFile("0_P10.mzXML")

mz <- m$spectrum$mass
tof <- f$spectrum$tof

A <- 6.1682474689786355
B <- sqrt(1e12/1164156.9998801197)
C <- 3884.868239229128
D <- -0.063083671657452864
E <- -34.362308485323794

a = D
b = A
c = B
d = C

root_mz <- c()

for(t in tof) {
  root_mz <- append(root_mz, cubic(a, b, c, d-t)[3])
}

root_mz = Re(root_mz)
predicted_mz = root_mz*root_mz*sign(root_mz)-E 

plot(mz, predicted_mz)
```
![index_vs_difference](https://user-images.githubusercontent.com/1210117/161944487-e5137d07-0b64-4f46-a90e-39c8637fce38.png)

It seems like the range up to this point is determined by a different function(?).

![mz_vs_difference](https://user-images.githubusercontent.com/1210117/161944739-0b0fbbf9-79f5-4c21-bc96-62843a1ab270.png)

**Comment by AlanRace** [comment]
Okay I think I have it now. It looks like the first part is quadratic and the rest is cubic. There is probably a much more efficient way to calculate this, but for testing here is the code:

```r
library("readBrukerFlexData")
library("readMzXmlData")

f <- readBrukerFlexFile("0_P10/1/1Ref/fid") 
m <- readMzXmlFile("0_P10.mzXML")

mz <- m$spectrum$mass
tof <- f$spectrum$tof

A <- 6.1682474689786355
B <- sqrt(1e12/1164156.9998801197)
C <- 3884.868239229128
D <- -0.063083671657452864
E <- -34.362308485323794

a = D
b = A
c = B
d = C

# Calculate sqrt(mz) as if it were quadratic, using formula in https://github.com/sgibb/readBrukerFlexData/blob/master/R/tof2mass-functions.R
# But keep track of the sign (whether tof is bigger than C)
tofMinusC = (tof-C)
sign = ((tofMinusC > 0) * 2)-1
to_sqrt = ((B * B) - (4 * A * (tofMinusC)))
root_mz = (-B + sqrt(abs(to_sqrt)))/(2 * A)

predicted_mz <- c()

for(i in 1:length(tof)) {
  # Check whether tof was larger than C
  if(sign[i] < 0) {
    # Use precalculated quadratic calibration
    predicted_mz <- append(predicted_mz, (root_mz[i])^2 * sign[i] - E)
  } else {
    # Assume cubic with the form a*x^3 + b*x^2 + c*x + (d - tof) 
    # where x = sqrt(mz)
    cur_root_mz = Re(polyroot(c(d-tof[i], c, b, a))[1])
    
    predicted_mz <- append(predicted_mz, (cur_root_mz)^2 * sign[i] - E)
  }
}

plot(mz, mz-predicted_mz)
```

This results in errors ~= 10^-6 at `m/z` ~= 2000, but I think that is okay for most purposes.

![calibration](https://user-images.githubusercontent.com/1210117/162174795-69b92a76-c89b-490d-9ff0-dfc97b25264f.png)

**Comment by sgibb** [comment]
@AlanRace that looks promising! Great stuff! I will give it a more detailed look in the next days!

**Comment by sgibb** [comment]
Dear @SamGG and @AlanRace thank you for your great work! Based on it I integrated the cubic calibration. I add you both as contributors to the `DESCRIPTION` file. Do you want to add some additional information (ORCID, email, ...?) there? Please feel free to ask for any changes.

Please find the cubic calibration in the [issue3-ctof2calibration](https://github.com/sgibb/readBrukerFlexData/tree/issue3-ctof2calibration) branch.
It would be great if you could review and test it. If you are both satisfied with it I am going to publish a new version on CRAN.
To test use:
```r
remotes::install_github("sgibb/readBrukerFlexData@issue3-ctof2calibration")
```

Something I currently not understand completely. It seems to be important to change `C - tof` into `tof - C` for the quadratic part (if you compare the equation in `tof2mass-functions.R` and `ntbcal-functions.R` (I renamed `C` into `D` in the cubic code.)). I would assume that the quadratic part is of this should be identical to the original tof to *mz* equation.

**Comment by AlanRace** [comment]
Looks great to me! I'll try and test it properly over the next few days.

Happy for you to add my ORCID (https://orcid.org/0000-0001-8996-2641) and email (alan.race@uni-marburg.de).

I guess if you wanted it to be consistent between quadratic and cubic part you could just do abs(tof - C)? I guess this is just a measure of distance (in time) away from this pivot point where the function swaps over.

**Comment by sgibb** [comment]
Finally we could close this issue. Thank you all for your support and patience!

I uploaded a new version (1.9.0) to CRAN.
