### ISSUE TITLE
Difference between "acqu" and "acqus" file?

### ISSUE THREAD

**Issue by herr-vogel** [sgibb/readBrukerFlexData#6]
Hello everyone. We are currently using MALDIquant to read the Bruker spectras of our client. Today we notices a problem. We received an export of the newest software version of the bruker biotyper. The readBrukerFlex failed to read it because there was no "acqu" file present only an "acqus" file. Could it be that this file not exported anymore?

**Comment by sgibb** [comment]
Just for the record, the current `readBrukerFlexData` version on CRAN (1.9.1) looks for the `acqus` file if the `acqu` file was not found. I have no idea why in general both files are present. They are identical (as backup?).

**Comment by herr-vogel** [comment]
I didn't got an official answer from bruker yer. But wat i saw until now they are identical.
